### ISSUE TITLE
Click doesn't activate portal in 1.14.4

### ISSUE THREAD

**Issue by FemStranger** [Sunekaer/YAMDA#11]
Right-click doesn't activate portal. (Attempted left-click too, no effect.)
Log: https://paste.feed-the-beast.com/view/9175137b

**Comment by Sunekaer** [comment]
Please try disabling all other mods then YAMDA, see if you still has issues, because i cant recreate this problem

**Comment by FemStranger** [comment]
Yeah, it works with no other mods. I guess I could isolate by adding them one by one. I have no other dimension mods, so I can't picture which one would interfere.

**Comment by Sunekaer** [comment]
Its most likely som mod adding ores

**Comment by FemStranger** [comment]
Okay, now I can't recreate it. X.x And I added back every mod one at a time...

**Comment by FemStranger** [comment]
Welp, at least it's working now.
