### ISSUE TITLE
Right click not working 1.14.4 Forge 20.0.45

### ISSUE THREAD

**Issue by Btaylor6199** [Sunekaer/YAMDA#13]
## Bug Report
Nothing is happening when right-clicked
## Steps to Reproduce (for bugs)
1. make the teleporter
2.Attempt to use then fail

## Logs
* Client/Server Log: 8/13/19 Client Log
* Crash Log:N/A

## Client Information

* Mod Version: YAMDA-4.0.1.jar
* Server/LAN/Single Player: Single Player

**Comment by Sunekaer** [comment]
Log? Other mods? Does it happen with yamda alone?

**Comment by inotsuoh** [comment]
I have this issue when I have Biomes O Plenty map generation. Will this work in the future with this or is that not possible? 

Edit: It works fine on any other Vanilla map generation. Only time the block/portal does not respond is when it is on a BoP map.

**Comment by Btaylor6199** [comment]
I entered the log on the website provided and I tried it by itself doesn't
work
