### ISSUE TITLE
Duped portal

### ISSUE THREAD

**Issue by Maxbanter45** [Sunekaer/YAMDA#14]
if you move your portal in the mining dimension then use it to get back to the overworld it creates another portal block

**Comment by Sunekaer** [comment]
Not going to be changed, if it doesn’t find an “receiver” portal with in set blocks it places one

**Comment by Maxbanter45** [comment]
okey thats fair i was wondering if it would be considered giving the blocks a linked id, thankyou for your hard work i really do enjoy the mod keep it up but god do silverfish scare me
