### ISSUE TITLE
Suggestion: Other biomes

### ISSUE THREAD

**Issue by Wissi** [Sunekaer/YAMDA#15]
Awesome work, love your mod.

Can report it's working fine on 1.14.4 with: 
Forge-28.0.81
YAMDA-4.0.1.jar

We do have a suggestion tho; would it be possible to have (maybe a config option) to assign other(s) Or several different biomes to your dimension?
Maybe even a config to just say "other biomes: true/false"?
Or player select Biome on creating/using portal first time, etc?
So players can also find and mine other blocks depending on biome?
Just some ideas.

Great work, thanks.

**Comment by Sunekaer** [comment]
The mod is using specific biome do to ores are based on specific biomes.
