### ISSUE TITLE
So many silverfish! D:

### ISSUE THREAD

**Issue by maidenofmara** [Sunekaer/YAMDA#16]
Hello I love this mod but for some reason everywhere I go has silverfish. I've had to close down three strip mine attempts because of the darn gnats. I noticed somebody suggested a disable hostile mob spawn option to config? That would be cool, or anything else that can fix the issue. I'm sorry if this isn't where to report this... I've never had any issues with a mod I really liked like this one.

**Comment by Knito58** [comment]
OK, that's possibly due to another mod. I did not see any silverfish in YAMDA 4.0.1.

**Comment by Sunekaer** [comment]
This mod doesnt add silverfish to the blocks in mining dim
