### ISSUE TITLE
Portal is not working when the mod is added to an existing world.

### ISSUE THREAD

**Issue by Tbizla** [Sunekaer/YAMDA#19]
## Bug Report

Portal is not working when the mod is added to an existing world.

## Steps to Reproduce (for bugs)

1. Create a new world first.
2. Then add the mod.
3. Place the portal
4. Right-click on the portal

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Mod Version: 4.0.1
* Server/LAN/Single Player: ATM-4 server & Single player

**Comment by DietmarKrause** [comment]
https://github.com/AllTheMods/ATM-4/issues/26

**Comment by Sunekaer** [comment]
Please test with the newest version of the mod(4.1.1) works fine for me there, else i need logs

**Comment by Tbizla** [comment]
i just did and 4.1.1 indeed works fine.
