### ISSUE TITLE
Druidcrafts Dreadfish swinning in mid-air in YAMDA mining dimension

### ISSUE THREAD

**Issue by DietmarKrause** [Sunekaer/YAMDA#20]
Druidcrafts Dreadfish swimming in mid-air in YAMDA mining dimension in modpack all the mods 4. I havent seen them elsewhere until now. This seems to be a bug.

**Comment by DietmarKrause** [comment]
https://github.com/MysticMods/Druidcraft/issues/10

**Comment by DietmarKrause** [comment]
https://github.com/AllTheMods/ATM-4/issues/39

**Comment by Boomflex** [comment]
It is intentional.

The Dreadfish are meant to fly.
