### ISSUE TITLE
[1.14.4] Beds and other bed-like objects explode while in the dimension

### ISSUE THREAD

**Issue by noobanidus** [Sunekaer/YAMDA#21]
I presume this is just a leftover bed-default that needs to be disabled.

**Comment by Sunekaer** [comment]
Not a bug, meant to happen.
Guess i could add a config for it

**Comment by noobanidus** [comment]
Ah... it's not really what I would've thought of as "expected behaviour". In Vanilla dimensions, it makes sense that you can't sleep in the nether (and it's very explicit) or the end. In a mining dimension that has a day/night cycle (I think?) it makes a little less sense.

**Comment by Sunekaer** [comment]
Well better than nothing 1.15.2 now have a config for this, with default allowing sleep
