### ISSUE TITLE
equally

### ISSUE THREAD

**Issue by Serzh812** [Sunekaer/YAMDA#22]
sun
[https://imgur.com/a/Q7PzQop](url)
night
[https://imgur.com/a/GNtOp9C](url)
rain
[https://imgur.com/a/LL7TMYJ](url)
config
[https://imgur.com/a/rlcQ2bd](url)

**Comment by Sunekaer** [comment]
What is the issue?

**Comment by Serzh812** [comment]
where the eternal day ?
rain is equally
the night is equally
screenshots of two worlds
