### ISSUE TITLE
1.15 port?

### ISSUE THREAD

**Issue by Wissi** [Sunekaer/YAMDA#25]
Didn't see any posts related, so we'd would like ask if you are planning to port over to 1.15?

We love your mod and it's always in out modpacks, we are starting with 1.15.2 and would love to include your awesome mod.
Sorry if it's been asked and answered, i could not find the topic.

Thanks for your great work.

**Comment by Sunekaer** [comment]
Working on it, just been busy

**Comment by Sunekaer** [comment]
https://www.curseforge.com/minecraft/mc-mods/yamda/files/2896776
First version bugs might be a thing
