### ISSUE TITLE
Not generating Andesite, Diorite, etc

### ISSUE THREAD

**Issue by InflamedSebi** [Sunekaer/YAMDA#26]
Seems like it is not generating Granite, Diorite, Andesite. Is there a way to enable this?

**Comment by Sunekaer** [comment]
What version of the mod? 
It uses vanilla generator from the biome Mountains

**Comment by Sunekaer** [comment]
Works in my test:
![image](https://user-images.githubusercontent.com/18720460/77862732-99500e00-721d-11ea-931d-a5f2b5f0ecea.png)

Are you playing a pack or?

**Comment by InflamedSebi** [comment]
4.1.1 and I did just add a few mods on my own ... imma do some more tests and remove some mods ...

**Comment by InflamedSebi** [comment]
Okay, Sorry, Quark is the mod with the bug.

**Comment by RoyalReject** [comment]
I have tired other dims that make mining work and they are able to spawn the quark stones but this one has not no matter what i tried

**Comment by InflamedSebi** [comment]
quark modifies generation per biome and does not generate everything in every biome, but you can disable this in the quark settings. As stated above this uses the Mountains biome to generate the mining dimension, which is totally fine due to the lack of emerald in other biomes. So to use this mod, you have to modify all generation changing mods to spawn their stuff in the mountains biome or look for a mining dimension mod that generates a world, where all biomes are present.

**Comment by RoyalReject** [comment]
I have the quack setting to spawn in every biome and it does in the overworld but still cant get it into this dim is there a setting i am missing or what did you use?

**Comment by RoyalReject** [comment]
[world.big_stone_clusters.marble]
			"Horizontal Size" = 80
			Rarity = 4
			"Min Y Level" = 20
			"Horizontal Variation" = 9
			Enabled = true
			"Max Y Level" = 80
			"Vertical Size" = 80
			"Vertical Variation" = 9

			[world.big_stone_clusters.marble.biomes]
				"Biome Types" = [""]
				"Is Blacklist" = true

			[world.big_stone_clusters.marble.dimensions]
				Dimensions = [""]
				"Is Blacklist" = true

**Comment by InflamedSebi** [comment]
Please check if it does spawn in the overworld specificly in Mountains biomes, I doubt that.
Also there is a bug report about big stone clusters having issues in the Quark repository, maybe thats part of it. Try disabling that feature completely and check again.
If quark stones are generating in the overword in Mountains biomes correctly but not in the mining dim pls try only with this mod and quark alone, to get rid of any other plugin, that might mess with it too, then come back and create your own issue, since this seems to be something unrelated to vanilla stones not being generated.
