### ISSUE TITLE
YAMDA vs JourneyMap

### ISSUE THREAD

**Issue by JudgeBrand** [Sunekaer/YAMDA#27]
## Bug Report
Using YAMDA with Enigmatica 5, when loading in to the mining dimension, it overwrites JourneyMap's overworld dimension.

Happy to help troubleshoot it, need to know what dimension the mining dimension ID is so that this can be linked to JourneyMap properly.

## Client Information
* Mod Version: YAMDA-5.0.2 (Minecraft 1.15)
* Server/LAN/Single Player: LAN

**Comment by Sunekaer** [comment]
Hi JudgeBrand

The dims ID is yamda:yamda_dim
