### ISSUE TITLE
portal not working

### ISSUE THREAD

**Issue by fistidgious** [Sunekaer/YAMDA#3]

**Comment by Sunekaer** [comment]
Whats not work?

**Comment by Sunekaer** [comment]
log?

**Comment by fistidgious** [comment]
ok so i only have this mod installed and i can craft the portal block but when i right click nothing happens.

**Comment by Sunekaer** [comment]
log?

**Comment by fistidgious** [comment]
not get a crash but will get the log for it 2 mins

**Comment by fistidgious** [comment]
[latest.log](https://github.com/Sunekaer/YAMDA/files/3331853/latest.log)

**Comment by Sunekaer** [comment]
Server or single player?

**Comment by fistidgious** [comment]
single player

**Comment by Sunekaer** [comment]
Thanks ill have a look as soon as i can

**Comment by fistidgious** [comment]
ok np thanx for looking :)

**Comment by Sunekaer** [comment]
Could you test with this one https://s1.sunekaer.com/files/YAMDA-3.0.1.jar  version 1.14.3-27.0.13 of forge

**Comment by fistidgious** [comment]
[latest.log](https://github.com/Sunekaer/YAMDA/files/3337755/latest.log)
ok tested same results

**Comment by Sunekaer** [comment]
That is weird, for both the version on Curseforge and this one is working for me

**Comment by Sunekaer** [comment]
Could you test this one https://s1.sunekaer.com/files/YAMDA-3.0.2.jar

**Comment by fistidgious** [comment]
[latest.log](https://github.com/Sunekaer/YAMDA/files/3340980/latest.log)
ok that version works in instance  1.14.3-forge27.0.13
[latest.log](https://github.com/Sunekaer/YAMDA/files/3340988/latest.log)
and it works in that instance  1.14.3-forge27.0.15
[latest.log](https://github.com/Sunekaer/YAMDA/files/3340991/latest.log)

first 2 logs are for a brand new world works fine in that, 3rd log is for my existing lets play world which is forge27.0.15 does not work in that so does not like existing worlds at a guess.

**Comment by Sunekaer** [comment]
Awesome, you can try and delete the yamda folder in you world and that way reset you mining dim and see if that helps

**Comment by fistidgious** [comment]
[latest.log](https://github.com/Sunekaer/YAMDA/files/3342334/latest.log)
k i did that deleted all info and config after making a backup on a seperate drive still same result no tp to a mine dime this is on my single player lets play forge 27.0.15

**Comment by fistidgious** [comment]
ok so i bit the bullet and re-started my letsplay world from fresh with the same seed and all works well, all i can think is that save had some corruption in it.
