### ISSUE TITLE
Portal sound volume

### ISSUE THREAD

**Issue by TheSnowyChickens** [Sunekaer/YAMDA#31]
## Bug Report
Hello,
is it possible to reduce the portal sound ? (or turn it off, with a new config option)

My ears die, if the master volume is at 50%+ and I go in the mining world. x=)

## Steps to Reproduce (for bugs)
1. turn on the sound
2. place a portal
3. go in the portal and wait a bit 

## Logs
* Logs: No logs, because I don't have any useful logs and it is only a sound problem.

## Client Information
* Mod Version: 5.0.2
* Server/LAN/Single Player: Singleplayer
* MC: 1.15.2
* Forge: 1.15.2-forge-31.1.44

**Comment by Sunekaer** [comment]
Hi,

Its the same volume as the nether portal.
The way the sound it played wont be change right now, might someday if i rewrite the mod
