### ISSUE TITLE
DIM ID Number ?

### ISSUE THREAD

**Issue by IchigoGames** [Sunekaer/YAMDA#34]
No DIM numbered id from what iv heard every dim has a number id as of 1.13+ but this does not so its not working when i try to add it to whitelist for pams mods. or am i wrong does this have a dim id other then yamda_dim ?

Minecraft 1.15.2
Forge 31.1.46
YAMDA-5.0.3

**Comment by Sunekaer** [comment]
We dont give dim's id numbers anymore, Minecraft auto assigns dims ids numbers we only give them and resource id yamda:yamda_dim

**Comment by IchigoGames** [comment]
so if i want to add this dim to pams whitelist dim list there no way ? it has to be a number pams does not suspport names

**Comment by IchigoGames** [comment]
ok i guess i'll ask pams to switch to resource id
