### ISSUE TITLE
1.14.3 right click on mining portal does nothing

### ISSUE THREAD

**Issue by FullMetalMaster** [Sunekaer/YAMDA#6]
lastest 1.14.3 portal does nothing? cant get in

**Comment by Sunekaer** [comment]
log?

**Comment by FullMetalMaster** [comment]
java.lang.NullPointerException: Dimension type must not be nulljava.lang.NullPointerException: Dimension type must not be null at org.apache.commons.lang3.Validate.notNull(Validate.java:225) ~[server-1.14.3-extra.jar:?] at net.minecraftforge.common.DimensionManager.getWorld(DimensionManager.java:157) ~[?:?] at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:958) ~[?:?] at com.sunekaer.mods.yamda.block.BlockPortal.func_220051_a(BlockPortal.java:58) ~[?:3.0.3] at net.minecraft.block.BlockState.func_215687_a(BlockState.java:274) ~[?:?] at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:347) ~

again 3.0.3 on 1.14.3

**Comment by FullMetalMaster** [comment]
doesnt work in single or mult

**Comment by Sunekaer** [comment]
full log https://pastebin.com/

**Comment by FullMetalMaster** [comment]
um ill paste some bc the log is to big ill do most of it???

**Comment by FullMetalMaster** [comment]
or can i send the log file some were?

**Comment by FullMetalMaster** [comment]
https://pastebin.com/rJbAEKz5

**Comment by Sunekaer** [comment]
Hmm weird, works fine in my dev env, what forge version?

**Comment by FullMetalMaster** [comment]
forge 1.14.3 27.0.25

**Comment by Sunekaer** [comment]
Hmm also works for me on 27.0.25, could you try creating a new world?

**Comment by FullMetalMaster** [comment]
ill try did it in single player already and nothing

**Comment by FullMetalMaster** [comment]
did u try downloading it form the site and loading the downloaded no dev file?

**Comment by FullMetalMaster** [comment]
no doesnt work even in a new world

**Comment by FullMetalMaster** [comment]
i can place them on each other with out shifting i dont think thats right? XD

**Comment by FullMetalMaster** [comment]
is there a command to get into it?

**Comment by Sunekaer** [comment]
Yes it works with the one from curseforge outside dev for me..
Placing them on top of each other is not a problem
No command

**Comment by FullMetalMaster** [comment]
okay is our configs different??

**Comment by FullMetalMaster** [comment]
found the problem doesnt seem to work with other mods/ mods the gen ores

**Comment by Sunekaer** [comment]
What mod is causing the conflict?
