### ISSUE TITLE
Dimension portal doesn't work in 1.14.3

### ISSUE THREAD

**Issue by FalcionVD** [Sunekaer/YAMDA#8]
Right clicking doesn't work with old and new world. Tried with forge 27.0.57 and 56. Version of the mod is the latest one, 3.0.3. I only have the U Team Core and Useful Backpacks mod installed along with yours,
[latest.log](https://github.com/Sunekaer/YAMDA/files/3405328/latest.log)
That's the latest log i have for it.

**Comment by Sunekaer** [comment]
Hmm that is very weird, I just installed forge 27.0.57 and those 3 mods via the twitch client, and I don't have this issue

**Comment by Sunekaer** [comment]
What version of java are you running?

**Comment by FalcionVD** [comment]
Version 8 Update 221 (build 1.8.0_211-b11)

**Comment by Sunekaer** [comment]
Hmm no clue whats causing it, cant recreate the issue

**Comment by FalcionVD** [comment]
Tbh i don't know myself either. The mod works if it installed by itself (and forge) so thats good but as soon as i installed back the u core and the backpack mod, it just stopped. Even reinstalled minecraft and do the whole process. Since it works for you, best i could guess is more of internal java problem or some weird things going on with my own pc instead of your mod. Really have no clue what's going on. So unfortunately i'll have to skip your mod and close this thread. Thanks a lot though for your time trying to fix my issue, really appreciate it.
